[project]
name = "architecture-patterns-python"
version = "0.1.0"
description = ""
authors = [
    { name = "Catarina Bressan", email = "catarina@catarinapbressan.org" },
]
license = { text = "CC BY-NC-ND 4.0" }
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "flask (>=3.1.3,<4.0.0)",
    "sqlalchemy (>=2.0.48,<3.0.0)",
    "python-dotenv (>=1.2.2,<2.0.0)",
]

[dependency-groups]
dev = [
    "ipdb (>=0.13.13,<0.14.0)",
    "pytest (>=9.0.2,<10.0.0)",
    "black (>=26.3.1,<27.0.0)",
    "flake8 (>=7.3.0,<8.0.0)",
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 100
