"""Changes Product version to string

Revision ID: d5363604873c
Revises: 8a3888963785
Create Date: 2026-04-07 14:59:00.303979

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d5363604873c"
down_revision: Union[str, Sequence[str], None] = "8a3888963785"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("products", sa.Column("version", sa.String(), nullable=True))
    op.drop_column("products", "version_number")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "products", sa.Column("version_number", sa.INTEGER(), autoincrement=False, nullable=True)
    )
    op.drop_column("products", "version")
    # ### end Alembic commands ###
